### ISSUE TITLE
Change installation scripts colors

### ISSUE THREAD

**Issue by PeeHaa** [PeeHaa/feedr#1]
Currently the installation script uses text colors for the CLI output severity modifiers.

It will probably look better if we used the background color instead. [This](http://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html#background-colors) might be helpful for determining the color codes to be used.

Note that some background probably need white text colors to make them more easily visible.

The installation script can be tested by running `composer install` in the project.

![install-script-cli](https://user-images.githubusercontent.com/1330296/47493593-53d52780-d858-11e8-95fd-3fcf794e4f6d.png)

**Comment by Nessworthy** [comment]
Happy to pick up! :)

**Comment by Nessworthy** [comment]
Thoughts? 
![image](https://user-images.githubusercontent.com/1154344/47532046-3b402e00-d8a7-11e8-836d-8de5257ef159.png)

**Comment by Nessworthy** [comment]
Added in some alignment, w/o braces
![image](https://user-images.githubusercontent.com/1154344/47532653-d84f9680-d8a8-11e8-8b33-f2f8ab43d6c4.png)

**Comment by Nessworthy** [comment]
Warning changed to "`WARN`" from "`ERROR`"
![image](https://user-images.githubusercontent.com/1154344/47532816-50b65780-d8a9-11e8-81bb-10c203da31b9.png)

IO prompts seem to be occasionaly faster than the previous log message, causing a break in formatting sometimes.

Text seems alright to be white for all types.

**Comment by Nessworthy** [comment]
![image](https://user-images.githubusercontent.com/1154344/47533005-f5d13000-d8a9-11e8-919a-ea24ce70c26a.png)
Added brackets back in to keep with the original format (don't want to break any parsers, etc.)
