### ISSUE TITLE
Don't run the installation script just for running the tests

### ISSUE THREAD

**Issue by PeeHaa** [PeeHaa/feedr#6]
Currently the installation script always runs upon running either `composer update` or `composer install` which is good for most cases.

However for just running the unit tests both locally and on travis there is no need to set up the database or github credentials.

Find a way to not run the installer on travis. Maybe a flag like `composer install --no-install` that's somehow get passed to the install script (as in the [Event here](https://github.com/PeeHaa/feedr/blob/master/src/Install/PostInstall.php#L15)) through composer is a possibility?

**Comment by mega6382** [comment]
I would really like to get a shot at this

**Comment by mega6382** [comment]
#12 PR has been created for this
